services:
  rustapp:
    container_name: rust-crud
    image: rust-crud:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: postgres://root:secret@db:5432/rust_crud
    ports:
      - '8082:8082'
    environment:
      DB_URL: postgres://root:secret@db:5432/rust_crud
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rust_crud
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}